name: publish

on:
  push:
    branches: [master]
  schedule:
  - cron: "* * * * *"

jobs:
  execute:
    name: execute
    runs-on: ubuntu-latest
    steps: 
      - name: check out repository 
        uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}
      
      - name: run
        run: docker-compose up

      - name: Check for modified files
        id: git-check
        run: echo ::set-output name=modified::$(if [ -n "$(git status --porcelain)" ]; then echo "true"; else echo "false"; fi)

      - name: Update changes in GitHub repository
        if: steps.git-check.outputs.modified == 'true'
        run:  |
          git config --global user.email "${{github.actor}}@users.noreply.github.com"
          git config --global user.name "${{github.actor}}"
          git add -A .
          git commit -m '[automated commit] saved new state'
          git push

    env:
      ENCRYPT_STATE: ${{ secrets.ENCRYPT_STATE }}
      RSS: ${{ secrets.RSS }}
      WEBHOOK: ${{ secrets.WEBHOOK }}
